# Generated by Django 4.2.7 on 2024-01-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('IdEnseignant', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('DateNaiss', models.DateField()),
                ('Genre', models.CharField(max_length=8)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Numtel', models.IntegerField()),
                ('Profil', models.ImageField(default='profil/default_profil.jpg', upload_to='profil/')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Genre', models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme')], max_length=8)),
                ('DateNaiss', models.DateField(verbose_name='Date de Naissance')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Profil', models.ImageField(default='profil/default_profil.jpg', upload_to='profil/')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'db_table': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('IdNiveau', models.AutoField(primary_key=True, serialize=False)),
                ('Niv', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('IdSemestre', models.AutoField(primary_key=True, serialize=False, verbose_name='idSemestre')),
                ('Numero', models.SmallIntegerField(verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Semestres',
                'verbose_name_plural': 'Semestres',
                'db_table': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('Code_ue', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=50)),
                ('Credit', models.IntegerField()),
                ('Type', models.CharField(choices=[('optionnelle', 'Optionnelle'), ('fondamentale', 'Fondamentale')], default='optionnelle', max_length=20)),
                ('idniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.niveau', verbose_name='idniv')),
                ('idsem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.semestres', verbose_name='idsem')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UE',
                'db_table': 'UE',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('IdEvaluation', models.AutoField(primary_key=True, serialize=False, verbose_name='IdEvaluation')),
                ('Type', models.CharField(choices=[('cc', 'CC'), ('tp', 'TP'), ('sn', 'SN')], default='cc', max_length=5)),
                ('Note', models.FloatField()),
                ('Code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ue')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.etudiant')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'Evaluations',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Niveau_etu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.niveau', verbose_name='Niveau_etu'),
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('Code_ec', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=50)),
                ('Code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ue')),
                ('Enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.enseignant')),
            ],
            options={
                'verbose_name': 'EC',
                'verbose_name_plural': 'EC',
                'db_table': 'EC',
            },
        ),
        migrations.CreateModel(
            name='Choisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ue')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.etudiant')),
            ],
            options={
                'verbose_name': 'Choisir',
                'verbose_name_plural': 'Choisir',
                'db_table': 'Choisir',
                'unique_together': {('Code_ue', 'Etudiant')},
            },
        ),
    ]
