# Generated by Django 4.2.7 on 2024-01-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='Libelle',
            field=models.CharField(max_length=255),
        ),
    ]
