# Generated by Django 4.2.7 on 2024-01-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_ue_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choisir_EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EC_Choisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ec')),
                ('Enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.enseignant')),
            ],
            options={
                'verbose_name': 'Choisir_EC',
                'verbose_name_plural': 'Choisir_EC',
                'db_table': 'Choisir_EC',
                'unique_together': {('Enseignant', 'EC_Choisit')},
            },
        ),
    ]
